http: 
  listener: 
    host: "0.0.0.0"
    port: "8082"
  requester: 
    customer: 
      sapi: 
        host: "0.0.0.0"
        pathCustomerState: "/api/customerState"
        port: "8081"
    verification:
      sapi:
        host: "0.0.0.0"
        pathVerification: "/api/verification"
        port: "8081"
    registration:
      sapi:
        host: "0.0.0.0"
        pathRegistration: "api/customers/registration"
        port: "8081"        
api:
  id: "17911774"
