http: 
  listener: 
    host: "0.0.0.0"
    port: "8082"
  requester: 
    customer: 
      sapi: 
        host: "0.0.0.0"
        pathCustomerState: "/api/customerState"
        port: "8081"
instanceID: "17815796"